---
title: "Untitled"
author: "Minh Chau Van Nguyen"
date: "24/09/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br><br>

```{r echo = FALSE}
df <- data.frame(AUC = 0.84,
                 Accuracy = 0.71,
                 F1score = 0.28,
                 A = 0.83,
                 B = 0.71,
                 C = 0.62,
                 D = 0.83,
                 E = 0.83,
                 F = 0.59,
                 G = 0.98, 
                 H = 0.88, 
                 I = 0.76, 
                 J = 0.87, 
                 K = 0.83,
                 L = 0.66
                 )

library(kableExtra)
library(knitr) 

df %>%
  knitr::kable(col.names = rep(c("AUC", "Accuracy", "F1-score"), 5)) %>%
  kable_classic_2(full_width=FALSE, html_font = "helvetica") %>%
  add_header_above(c("Imbalanced" = 3, "Balanced" = 3, "Balanced" = 3, "Balanced" = 3, "Balanced" = 3), bold = TRUE, color = "dodgerblue") %>%
  add_header_above(c("Non-full model" = 6, "Full model" = 3, "\\(\\chi^2\\) model" = 3, "F-score model" = 3), bold = TRUE, color = "white", background = "#D7261E", align = "|c|") %>%
  footnote(symbol = c("<small>The AUC and F1-score included here are macro-averaged</small>"), escape = FALSE
  )
```